require "activeadmin" 
require "activeadmin_addons"  
require "active_admin_role" 
require "devise" 
require "draper" 
require "pundit" 
require "enumerize"  
require "ckeditor"  
require "chartkick"  
require "groupdate"   
 
require "wordpress/backend/authorization"  
require "wordpress/backend/engine"  
require "wordpress/backend/paranoia/core"   
require "wordpress/backend/batch/dsl"  
require "wordpress/backend/state_machine/dsl"    
require "wordpress/backend/controller/active_admin_base"  
